/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as RegistrarRouteImport } from './routes/registrar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SolicitacoesRouteImport } from './routes/solicitacoes'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BacklogRouteImport } from './routes/backlog'
import { Route as IndexRouteImport } from './routes/index'

const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrarRoute = RegistrarRouteImport.update({
  id: '/registrar',
  path: '/registrar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitacoesRoute = SolicitacoesRouteImport.update({
  id: '/solicitacoes',
  path: '/solicitacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BacklogRoute = BacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backlog': typeof BacklogRoute
  '/dashboard': typeof DashboardRoute
  '/historico': typeof HistoricoRoute
  '/roadmap': typeof RoadmapRoute
  '/solicitacoes': typeof SolicitacoesRoute
  '/login': typeof LoginRoute
  '/registrar': typeof RegistrarRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backlog': typeof BacklogRoute
  '/dashboard': typeof DashboardRoute
  '/historico': typeof HistoricoRoute
  '/roadmap': typeof RoadmapRoute
  '/solicitacoes': typeof SolicitacoesRoute
  '/login': typeof LoginRoute
  '/registrar': typeof RegistrarRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backlog': typeof BacklogRoute
  '/dashboard': typeof DashboardRoute
  '/historico': typeof HistoricoRoute
  '/roadmap': typeof RoadmapRoute
  '/solicitacoes': typeof SolicitacoesRoute
  '/login': typeof LoginRoute
  '/registrar': typeof RegistrarRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/backlog' | '/dashboard' | '/historico' | '/roadmap' | '/solicitacoes' | '/login' | '/registrar' | '/admin/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/backlog' | '/dashboard' | '/historico' | '/roadmap' | '/solicitacoes' | '/login' | '/registrar' | '/admin/usuarios'
  id:
    | '__root__'
    | '/'
    | '/backlog'
    | '/dashboard'
    | '/historico'
    | '/roadmap'
    | '/solicitacoes'
    | '/login'
    | '/registrar'
    | '/admin/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacklogRoute: typeof BacklogRoute
  DashboardRoute: typeof DashboardRoute
  HistoricoRoute: typeof HistoricoRoute
  RoadmapRoute: typeof RoadmapRoute
  SolicitacoesRoute: typeof SolicitacoesRoute
  LoginRoute: typeof LoginRoute
  RegistrarRoute: typeof RegistrarRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solicitacoes': {
      id: '/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/solicitacoes'
      preLoaderRoute: typeof SolicitacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backlog': {
      id: '/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof BacklogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrar': {
      id: '/registrar'
      path: '/registrar'
      fullPath: '/registrar'
      preLoaderRoute: typeof RegistrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacklogRoute: BacklogRoute,
  DashboardRoute: DashboardRoute,
  HistoricoRoute: HistoricoRoute,
  RoadmapRoute: RoadmapRoute,
  SolicitacoesRoute: SolicitacoesRoute,
  LoginRoute: LoginRoute,
  RegistrarRoute: RegistrarRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
