/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RegistrarRouteImport } from './routes/registrar'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedComprasRouteImport } from './routes/_authenticated._compras'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated._documentos'
import { Route as AuthenticatedGestaoRouteImport } from './routes/_authenticated._gestao'
import { Route as AuthenticatedToyotaRouteImport } from './routes/_authenticated._toyota'
import { Route as AuthenticatedDocumentosDocumentosRouteImport } from './routes/_authenticated._documentos.documentos'
import { Route as AuthenticatedGestaoBacklogRouteImport } from './routes/_authenticated._gestao.backlog'
import { Route as AuthenticatedGestaoDashboardRouteImport } from './routes/_authenticated._gestao.dashboard'
import { Route as AuthenticatedGestaoHistoricoRouteImport } from './routes/_authenticated._gestao.historico'
import { Route as AuthenticatedGestaoProjetosRouteImport } from './routes/_authenticated._gestao.projetos'
import { Route as AuthenticatedGestaoRoadmapRouteImport } from './routes/_authenticated._gestao.roadmap'
import { Route as AuthenticatedGestaoSolicitacoesRouteImport } from './routes/_authenticated._gestao.solicitacoes'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated.admin.usuarios'
import { Route as AuthenticatedComprasComprasIndexRouteImport } from './routes/_authenticated._compras.compras.index'
import { Route as AuthenticatedComprasComprasIdRouteImport } from './routes/_authenticated._compras.compras.$id'
import { Route as AuthenticatedComprasComprasConfiguracoesRouteImport } from './routes/_authenticated._compras.compras.configuracoes'
import { Route as AuthenticatedComprasComprasNovoRouteImport } from './routes/_authenticated._compras.compras.novo'
import { Route as AuthenticatedToyotaToyotaConfiguracoesRouteImport } from './routes/_authenticated._toyota.toyota.configuracoes'
import { Route as AuthenticatedToyotaToyotaElegiveisRouteImport } from './routes/_authenticated._toyota.toyota.elegiveis'
import { Route as AuthenticatedToyotaToyotaFilaPosvendasRouteImport } from './routes/_authenticated._toyota.toyota.fila-posvendas'
import { Route as AuthenticatedToyotaToyotaFilaPreparadorRouteImport } from './routes/_authenticated._toyota.toyota.fila-preparador'
import { Route as AuthenticatedToyotaToyotaPainelRouteImport } from './routes/_authenticated._toyota.toyota.painel'
import { Route as AuthenticatedToyotaToyotaPainelGeralRouteImport } from './routes/_authenticated._toyota.toyota.painel-geral'
import { Route as AuthenticatedToyotaToyotaRegrasRouteImport } from './routes/_authenticated._toyota.toyota.regras'
import { Route as AuthenticatedToyotaToyotaRevisoesRouteImport } from './routes/_authenticated._toyota.toyota.revisoes'
import { Route as ApiPublicCronVerificarNotificacoesRouteImport } from './routes/api/public/cron/verificar-notificacoes'
import { Route as ApiPublicHooksNotificarVencimentosRouteImport } from './routes/api/public/hooks/notificar-vencimentos'
import { Route as ApiPublicHooksNotificarVencimentosTestRouteImport } from './routes/api/public/hooks/notificar-vencimentos-test'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as AuthenticatedToyotaToyotaEstoqueImportarRouteImport } from './routes/_authenticated._toyota.toyota.estoque.importar'
import { Route as AuthenticatedToyotaToyotaRevisoesNovaRouteImport } from './routes/_authenticated._toyota.toyota.revisoes.nova'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrarRoute = RegistrarRouteImport.update({
  id: '/registrar',
  path: '/registrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComprasRoute = AuthenticatedComprasRouteImport.update({
  id: '/_compras',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/_documentos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGestaoRoute = AuthenticatedGestaoRouteImport.update({
  id: '/_gestao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedToyotaRoute = AuthenticatedToyotaRouteImport.update({
  id: '/_toyota',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentosDocumentosRoute =
  AuthenticatedDocumentosDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => AuthenticatedDocumentosRoute,
  } as any)
const AuthenticatedGestaoBacklogRoute =
  AuthenticatedGestaoBacklogRouteImport.update({
    id: '/backlog',
    path: '/backlog',
    getParentRoute: () => AuthenticatedGestaoRoute,
  } as any)
const AuthenticatedGestaoDashboardRoute =
  AuthenticatedGestaoDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedGestaoRoute,
  } as any)
const AuthenticatedGestaoHistoricoRoute =
  AuthenticatedGestaoHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => AuthenticatedGestaoRoute,
  } as any)
const AuthenticatedGestaoProjetosRoute =
  AuthenticatedGestaoProjetosRouteImport.update({
    id: '/projetos',
    path: '/projetos',
    getParentRoute: () => AuthenticatedGestaoRoute,
  } as any)
const AuthenticatedGestaoRoadmapRoute =
  AuthenticatedGestaoRoadmapRouteImport.update({
    id: '/roadmap',
    path: '/roadmap',
    getParentRoute: () => AuthenticatedGestaoRoute,
  } as any)
const AuthenticatedGestaoSolicitacoesRoute =
  AuthenticatedGestaoSolicitacoesRouteImport.update({
    id: '/solicitacoes',
    path: '/solicitacoes',
    getParentRoute: () => AuthenticatedGestaoRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComprasComprasIndexRoute =
  AuthenticatedComprasComprasIndexRouteImport.update({
    id: '/compras/',
    path: '/compras/',
    getParentRoute: () => AuthenticatedComprasRoute,
  } as any)
const AuthenticatedComprasComprasIdRoute =
  AuthenticatedComprasComprasIdRouteImport.update({
    id: '/compras/$id',
    path: '/compras/$id',
    getParentRoute: () => AuthenticatedComprasRoute,
  } as any)
const AuthenticatedComprasComprasConfiguracoesRoute =
  AuthenticatedComprasComprasConfiguracoesRouteImport.update({
    id: '/compras/configuracoes',
    path: '/compras/configuracoes',
    getParentRoute: () => AuthenticatedComprasRoute,
  } as any)
const AuthenticatedComprasComprasNovoRoute =
  AuthenticatedComprasComprasNovoRouteImport.update({
    id: '/compras/novo',
    path: '/compras/novo',
    getParentRoute: () => AuthenticatedComprasRoute,
  } as any)
const AuthenticatedToyotaToyotaConfiguracoesRoute =
  AuthenticatedToyotaToyotaConfiguracoesRouteImport.update({
    id: '/toyota/configuracoes',
    path: '/toyota/configuracoes',
    getParentRoute: () => AuthenticatedToyotaRoute,
  } as any)
const AuthenticatedToyotaToyotaElegiveisRoute =
  AuthenticatedToyotaToyotaElegiveisRouteImport.update({
    id: '/toyota/elegiveis',
    path: '/toyota/elegiveis',
    getParentRoute: () => AuthenticatedToyotaRoute,
  } as any)
const AuthenticatedToyotaToyotaFilaPosvendasRoute =
  AuthenticatedToyotaToyotaFilaPosvendasRouteImport.update({
    id: '/toyota/fila-posvendas',
    path: '/toyota/fila-posvendas',
    getParentRoute: () => AuthenticatedToyotaRoute,
  } as any)
const AuthenticatedToyotaToyotaFilaPreparadorRoute =
  AuthenticatedToyotaToyotaFilaPreparadorRouteImport.update({
    id: '/toyota/fila-preparador',
    path: '/toyota/fila-preparador',
    getParentRoute: () => AuthenticatedToyotaRoute,
  } as any)
const AuthenticatedToyotaToyotaPainelRoute =
  AuthenticatedToyotaToyotaPainelRouteImport.update({
    id: '/toyota/painel',
    path: '/toyota/painel',
    getParentRoute: () => AuthenticatedToyotaRoute,
  } as any)
const AuthenticatedToyotaToyotaPainelGeralRoute =
  AuthenticatedToyotaToyotaPainelGeralRouteImport.update({
    id: '/toyota/painel-geral',
    path: '/toyota/painel-geral',
    getParentRoute: () => AuthenticatedToyotaRoute,
  } as any)
const AuthenticatedToyotaToyotaRegrasRoute =
  AuthenticatedToyotaToyotaRegrasRouteImport.update({
    id: '/toyota/regras',
    path: '/toyota/regras',
    getParentRoute: () => AuthenticatedToyotaRoute,
  } as any)
const AuthenticatedToyotaToyotaRevisoesRoute =
  AuthenticatedToyotaToyotaRevisoesRouteImport.update({
    id: '/toyota/revisoes',
    path: '/toyota/revisoes',
    getParentRoute: () => AuthenticatedToyotaRoute,
  } as any)
const ApiPublicCronVerificarNotificacoesRoute =
  ApiPublicCronVerificarNotificacoesRouteImport.update({
    id: '/api/public/cron/verificar-notificacoes',
    path: '/api/public/cron/verificar-notificacoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNotificarVencimentosRoute =
  ApiPublicHooksNotificarVencimentosRouteImport.update({
    id: '/api/public/hooks/notificar-vencimentos',
    path: '/api/public/hooks/notificar-vencimentos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNotificarVencimentosTestRoute =
  ApiPublicHooksNotificarVencimentosTestRouteImport.update({
    id: '/api/public/hooks/notificar-vencimentos-test',
    path: '/api/public/hooks/notificar-vencimentos-test',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedToyotaToyotaEstoqueImportarRoute =
  AuthenticatedToyotaToyotaEstoqueImportarRouteImport.update({
    id: '/toyota/estoque/importar',
    path: '/toyota/estoque/importar',
    getParentRoute: () => AuthenticatedToyotaRoute,
  } as any)
const AuthenticatedToyotaToyotaRevisoesNovaRoute =
  AuthenticatedToyotaToyotaRevisoesNovaRouteImport.update({
    id: '/nova',
    path: '/nova',
    getParentRoute: () => AuthenticatedToyotaToyotaRevisoesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/registrar': typeof RegistrarRoute
  '/documentos': typeof AuthenticatedDocumentosDocumentosRoute
  '/backlog': typeof AuthenticatedGestaoBacklogRoute
  '/dashboard': typeof AuthenticatedGestaoDashboardRoute
  '/historico': typeof AuthenticatedGestaoHistoricoRoute
  '/projetos': typeof AuthenticatedGestaoProjetosRoute
  '/roadmap': typeof AuthenticatedGestaoRoadmapRoute
  '/solicitacoes': typeof AuthenticatedGestaoSolicitacoesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/compras/$id': typeof AuthenticatedComprasComprasIdRoute
  '/compras/configuracoes': typeof AuthenticatedComprasComprasConfiguracoesRoute
  '/compras/novo': typeof AuthenticatedComprasComprasNovoRoute
  '/toyota/configuracoes': typeof AuthenticatedToyotaToyotaConfiguracoesRoute
  '/toyota/elegiveis': typeof AuthenticatedToyotaToyotaElegiveisRoute
  '/toyota/fila-posvendas': typeof AuthenticatedToyotaToyotaFilaPosvendasRoute
  '/toyota/fila-preparador': typeof AuthenticatedToyotaToyotaFilaPreparadorRoute
  '/toyota/painel': typeof AuthenticatedToyotaToyotaPainelRoute
  '/toyota/painel-geral': typeof AuthenticatedToyotaToyotaPainelGeralRoute
  '/toyota/regras': typeof AuthenticatedToyotaToyotaRegrasRoute
  '/toyota/revisoes': typeof AuthenticatedToyotaToyotaRevisoesRouteWithChildren
  '/api/public/cron/verificar-notificacoes': typeof ApiPublicCronVerificarNotificacoesRoute
  '/api/public/hooks/notificar-vencimentos': typeof ApiPublicHooksNotificarVencimentosRoute
  '/api/public/hooks/notificar-vencimentos-test': typeof ApiPublicHooksNotificarVencimentosTestRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/compras/': typeof AuthenticatedComprasComprasIndexRoute
  '/toyota/estoque/importar': typeof AuthenticatedToyotaToyotaEstoqueImportarRoute
  '/toyota/revisoes/nova': typeof AuthenticatedToyotaToyotaRevisoesNovaRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/registrar': typeof RegistrarRoute
  '/': typeof AuthenticatedIndexRoute
  '/documentos': typeof AuthenticatedDocumentosDocumentosRoute
  '/backlog': typeof AuthenticatedGestaoBacklogRoute
  '/dashboard': typeof AuthenticatedGestaoDashboardRoute
  '/historico': typeof AuthenticatedGestaoHistoricoRoute
  '/projetos': typeof AuthenticatedGestaoProjetosRoute
  '/roadmap': typeof AuthenticatedGestaoRoadmapRoute
  '/solicitacoes': typeof AuthenticatedGestaoSolicitacoesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/compras/$id': typeof AuthenticatedComprasComprasIdRoute
  '/compras/configuracoes': typeof AuthenticatedComprasComprasConfiguracoesRoute
  '/compras/novo': typeof AuthenticatedComprasComprasNovoRoute
  '/toyota/configuracoes': typeof AuthenticatedToyotaToyotaConfiguracoesRoute
  '/toyota/elegiveis': typeof AuthenticatedToyotaToyotaElegiveisRoute
  '/toyota/fila-posvendas': typeof AuthenticatedToyotaToyotaFilaPosvendasRoute
  '/toyota/fila-preparador': typeof AuthenticatedToyotaToyotaFilaPreparadorRoute
  '/toyota/painel': typeof AuthenticatedToyotaToyotaPainelRoute
  '/toyota/painel-geral': typeof AuthenticatedToyotaToyotaPainelGeralRoute
  '/toyota/regras': typeof AuthenticatedToyotaToyotaRegrasRoute
  '/toyota/revisoes': typeof AuthenticatedToyotaToyotaRevisoesRouteWithChildren
  '/api/public/cron/verificar-notificacoes': typeof ApiPublicCronVerificarNotificacoesRoute
  '/api/public/hooks/notificar-vencimentos': typeof ApiPublicHooksNotificarVencimentosRoute
  '/api/public/hooks/notificar-vencimentos-test': typeof ApiPublicHooksNotificarVencimentosTestRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/compras': typeof AuthenticatedComprasComprasIndexRoute
  '/toyota/estoque/importar': typeof AuthenticatedToyotaToyotaEstoqueImportarRoute
  '/toyota/revisoes/nova': typeof AuthenticatedToyotaToyotaRevisoesNovaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/registrar': typeof RegistrarRoute
  '/_authenticated/_compras': typeof AuthenticatedComprasRouteWithChildren
  '/_authenticated/_documentos': typeof AuthenticatedDocumentosRouteWithChildren
  '/_authenticated/_gestao': typeof AuthenticatedGestaoRouteWithChildren
  '/_authenticated/_toyota': typeof AuthenticatedToyotaRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/_documentos/documentos': typeof AuthenticatedDocumentosDocumentosRoute
  '/_authenticated/_gestao/backlog': typeof AuthenticatedGestaoBacklogRoute
  '/_authenticated/_gestao/dashboard': typeof AuthenticatedGestaoDashboardRoute
  '/_authenticated/_gestao/historico': typeof AuthenticatedGestaoHistoricoRoute
  '/_authenticated/_gestao/projetos': typeof AuthenticatedGestaoProjetosRoute
  '/_authenticated/_gestao/roadmap': typeof AuthenticatedGestaoRoadmapRoute
  '/_authenticated/_gestao/solicitacoes': typeof AuthenticatedGestaoSolicitacoesRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/_compras/compras/$id': typeof AuthenticatedComprasComprasIdRoute
  '/_authenticated/_compras/compras/configuracoes': typeof AuthenticatedComprasComprasConfiguracoesRoute
  '/_authenticated/_compras/compras/novo': typeof AuthenticatedComprasComprasNovoRoute
  '/_authenticated/_toyota/toyota/configuracoes': typeof AuthenticatedToyotaToyotaConfiguracoesRoute
  '/_authenticated/_toyota/toyota/elegiveis': typeof AuthenticatedToyotaToyotaElegiveisRoute
  '/_authenticated/_toyota/toyota/fila-posvendas': typeof AuthenticatedToyotaToyotaFilaPosvendasRoute
  '/_authenticated/_toyota/toyota/fila-preparador': typeof AuthenticatedToyotaToyotaFilaPreparadorRoute
  '/_authenticated/_toyota/toyota/painel': typeof AuthenticatedToyotaToyotaPainelRoute
  '/_authenticated/_toyota/toyota/painel-geral': typeof AuthenticatedToyotaToyotaPainelGeralRoute
  '/_authenticated/_toyota/toyota/regras': typeof AuthenticatedToyotaToyotaRegrasRoute
  '/_authenticated/_toyota/toyota/revisoes': typeof AuthenticatedToyotaToyotaRevisoesRouteWithChildren
  '/api/public/cron/verificar-notificacoes': typeof ApiPublicCronVerificarNotificacoesRoute
  '/api/public/hooks/notificar-vencimentos': typeof ApiPublicHooksNotificarVencimentosRoute
  '/api/public/hooks/notificar-vencimentos-test': typeof ApiPublicHooksNotificarVencimentosTestRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/_compras/compras/': typeof AuthenticatedComprasComprasIndexRoute
  '/_authenticated/_toyota/toyota/estoque/importar': typeof AuthenticatedToyotaToyotaEstoqueImportarRoute
  '/_authenticated/_toyota/toyota/revisoes/nova': typeof AuthenticatedToyotaToyotaRevisoesNovaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recuperar-senha'
    | '/registrar'
    | '/documentos'
    | '/backlog'
    | '/dashboard'
    | '/historico'
    | '/projetos'
    | '/roadmap'
    | '/solicitacoes'
    | '/admin/usuarios'
    | '/compras/$id'
    | '/compras/configuracoes'
    | '/compras/novo'
    | '/toyota/configuracoes'
    | '/toyota/elegiveis'
    | '/toyota/fila-posvendas'
    | '/toyota/fila-preparador'
    | '/toyota/painel'
    | '/toyota/painel-geral'
    | '/toyota/regras'
    | '/toyota/revisoes'
    | '/api/public/cron/verificar-notificacoes'
    | '/api/public/hooks/notificar-vencimentos'
    | '/api/public/hooks/notificar-vencimentos-test'
    | '/lovable/email/queue/process'
    | '/compras/'
    | '/toyota/estoque/importar'
    | '/toyota/revisoes/nova'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recuperar-senha'
    | '/registrar'
    | '/'
    | '/documentos'
    | '/backlog'
    | '/dashboard'
    | '/historico'
    | '/projetos'
    | '/roadmap'
    | '/solicitacoes'
    | '/admin/usuarios'
    | '/compras/$id'
    | '/compras/configuracoes'
    | '/compras/novo'
    | '/toyota/configuracoes'
    | '/toyota/elegiveis'
    | '/toyota/fila-posvendas'
    | '/toyota/fila-preparador'
    | '/toyota/painel'
    | '/toyota/painel-geral'
    | '/toyota/regras'
    | '/toyota/revisoes'
    | '/api/public/cron/verificar-notificacoes'
    | '/api/public/hooks/notificar-vencimentos'
    | '/api/public/hooks/notificar-vencimentos-test'
    | '/lovable/email/queue/process'
    | '/compras'
    | '/toyota/estoque/importar'
    | '/toyota/revisoes/nova'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/recuperar-senha'
    | '/registrar'
    | '/_authenticated/_compras'
    | '/_authenticated/_documentos'
    | '/_authenticated/_gestao'
    | '/_authenticated/_toyota'
    | '/_authenticated/'
    | '/_authenticated/_documentos/documentos'
    | '/_authenticated/_gestao/backlog'
    | '/_authenticated/_gestao/dashboard'
    | '/_authenticated/_gestao/historico'
    | '/_authenticated/_gestao/projetos'
    | '/_authenticated/_gestao/roadmap'
    | '/_authenticated/_gestao/solicitacoes'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/_compras/compras/$id'
    | '/_authenticated/_compras/compras/configuracoes'
    | '/_authenticated/_compras/compras/novo'
    | '/_authenticated/_toyota/toyota/configuracoes'
    | '/_authenticated/_toyota/toyota/elegiveis'
    | '/_authenticated/_toyota/toyota/fila-posvendas'
    | '/_authenticated/_toyota/toyota/fila-preparador'
    | '/_authenticated/_toyota/toyota/painel'
    | '/_authenticated/_toyota/toyota/painel-geral'
    | '/_authenticated/_toyota/toyota/regras'
    | '/_authenticated/_toyota/toyota/revisoes'
    | '/api/public/cron/verificar-notificacoes'
    | '/api/public/hooks/notificar-vencimentos'
    | '/api/public/hooks/notificar-vencimentos-test'
    | '/lovable/email/queue/process'
    | '/_authenticated/_compras/compras/'
    | '/_authenticated/_toyota/toyota/estoque/importar'
    | '/_authenticated/_toyota/toyota/revisoes/nova'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RegistrarRoute: typeof RegistrarRoute
  ApiPublicCronVerificarNotificacoesRoute: typeof ApiPublicCronVerificarNotificacoesRoute
  ApiPublicHooksNotificarVencimentosRoute: typeof ApiPublicHooksNotificarVencimentosRoute
  ApiPublicHooksNotificarVencimentosTestRoute: typeof ApiPublicHooksNotificarVencimentosTestRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrar': {
      id: '/registrar'
      path: '/registrar'
      fullPath: '/registrar'
      preLoaderRoute: typeof RegistrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_compras': {
      id: '/_authenticated/_compras'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedComprasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_documentos': {
      id: '/_authenticated/_documentos'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_gestao': {
      id: '/_authenticated/_gestao'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedGestaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_toyota': {
      id: '/_authenticated/_toyota'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedToyotaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_documentos/documentos': {
      id: '/_authenticated/_documentos/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosDocumentosRouteImport
      parentRoute: typeof AuthenticatedDocumentosRoute
    }
    '/_authenticated/_gestao/backlog': {
      id: '/_authenticated/_gestao/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof AuthenticatedGestaoBacklogRouteImport
      parentRoute: typeof AuthenticatedGestaoRoute
    }
    '/_authenticated/_gestao/dashboard': {
      id: '/_authenticated/_gestao/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedGestaoDashboardRouteImport
      parentRoute: typeof AuthenticatedGestaoRoute
    }
    '/_authenticated/_gestao/historico': {
      id: '/_authenticated/_gestao/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedGestaoHistoricoRouteImport
      parentRoute: typeof AuthenticatedGestaoRoute
    }
    '/_authenticated/_gestao/projetos': {
      id: '/_authenticated/_gestao/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof AuthenticatedGestaoProjetosRouteImport
      parentRoute: typeof AuthenticatedGestaoRoute
    }
    '/_authenticated/_gestao/roadmap': {
      id: '/_authenticated/_gestao/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedGestaoRoadmapRouteImport
      parentRoute: typeof AuthenticatedGestaoRoute
    }
    '/_authenticated/_gestao/solicitacoes': {
      id: '/_authenticated/_gestao/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/solicitacoes'
      preLoaderRoute: typeof AuthenticatedGestaoSolicitacoesRouteImport
      parentRoute: typeof AuthenticatedGestaoRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_compras/compras/': {
      id: '/_authenticated/_compras/compras/'
      path: '/compras'
      fullPath: '/compras/'
      preLoaderRoute: typeof AuthenticatedComprasComprasIndexRouteImport
      parentRoute: typeof AuthenticatedComprasRoute
    }
    '/_authenticated/_compras/compras/$id': {
      id: '/_authenticated/_compras/compras/$id'
      path: '/compras/$id'
      fullPath: '/compras/$id'
      preLoaderRoute: typeof AuthenticatedComprasComprasIdRouteImport
      parentRoute: typeof AuthenticatedComprasRoute
    }
    '/_authenticated/_compras/compras/configuracoes': {
      id: '/_authenticated/_compras/compras/configuracoes'
      path: '/compras/configuracoes'
      fullPath: '/compras/configuracoes'
      preLoaderRoute: typeof AuthenticatedComprasComprasConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedComprasRoute
    }
    '/_authenticated/_compras/compras/novo': {
      id: '/_authenticated/_compras/compras/novo'
      path: '/compras/novo'
      fullPath: '/compras/novo'
      preLoaderRoute: typeof AuthenticatedComprasComprasNovoRouteImport
      parentRoute: typeof AuthenticatedComprasRoute
    }
    '/_authenticated/_toyota/toyota/configuracoes': {
      id: '/_authenticated/_toyota/toyota/configuracoes'
      path: '/toyota/configuracoes'
      fullPath: '/toyota/configuracoes'
      preLoaderRoute: typeof AuthenticatedToyotaToyotaConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedToyotaRoute
    }
    '/_authenticated/_toyota/toyota/elegiveis': {
      id: '/_authenticated/_toyota/toyota/elegiveis'
      path: '/toyota/elegiveis'
      fullPath: '/toyota/elegiveis'
      preLoaderRoute: typeof AuthenticatedToyotaToyotaElegiveisRouteImport
      parentRoute: typeof AuthenticatedToyotaRoute
    }
    '/_authenticated/_toyota/toyota/fila-posvendas': {
      id: '/_authenticated/_toyota/toyota/fila-posvendas'
      path: '/toyota/fila-posvendas'
      fullPath: '/toyota/fila-posvendas'
      preLoaderRoute: typeof AuthenticatedToyotaToyotaFilaPosvendasRouteImport
      parentRoute: typeof AuthenticatedToyotaRoute
    }
    '/_authenticated/_toyota/toyota/fila-preparador': {
      id: '/_authenticated/_toyota/toyota/fila-preparador'
      path: '/toyota/fila-preparador'
      fullPath: '/toyota/fila-preparador'
      preLoaderRoute: typeof AuthenticatedToyotaToyotaFilaPreparadorRouteImport
      parentRoute: typeof AuthenticatedToyotaRoute
    }
    '/_authenticated/_toyota/toyota/painel': {
      id: '/_authenticated/_toyota/toyota/painel'
      path: '/toyota/painel'
      fullPath: '/toyota/painel'
      preLoaderRoute: typeof AuthenticatedToyotaToyotaPainelRouteImport
      parentRoute: typeof AuthenticatedToyotaRoute
    }
    '/_authenticated/_toyota/toyota/painel-geral': {
      id: '/_authenticated/_toyota/toyota/painel-geral'
      path: '/toyota/painel-geral'
      fullPath: '/toyota/painel-geral'
      preLoaderRoute: typeof AuthenticatedToyotaToyotaPainelGeralRouteImport
      parentRoute: typeof AuthenticatedToyotaRoute
    }
    '/_authenticated/_toyota/toyota/regras': {
      id: '/_authenticated/_toyota/toyota/regras'
      path: '/toyota/regras'
      fullPath: '/toyota/regras'
      preLoaderRoute: typeof AuthenticatedToyotaToyotaRegrasRouteImport
      parentRoute: typeof AuthenticatedToyotaRoute
    }
    '/_authenticated/_toyota/toyota/revisoes': {
      id: '/_authenticated/_toyota/toyota/revisoes'
      path: '/toyota/revisoes'
      fullPath: '/toyota/revisoes'
      preLoaderRoute: typeof AuthenticatedToyotaToyotaRevisoesRouteImport
      parentRoute: typeof AuthenticatedToyotaRoute
    }
    '/api/public/cron/verificar-notificacoes': {
      id: '/api/public/cron/verificar-notificacoes'
      path: '/api/public/cron/verificar-notificacoes'
      fullPath: '/api/public/cron/verificar-notificacoes'
      preLoaderRoute: typeof ApiPublicCronVerificarNotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/notificar-vencimentos': {
      id: '/api/public/hooks/notificar-vencimentos'
      path: '/api/public/hooks/notificar-vencimentos'
      fullPath: '/api/public/hooks/notificar-vencimentos'
      preLoaderRoute: typeof ApiPublicHooksNotificarVencimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/notificar-vencimentos-test': {
      id: '/api/public/hooks/notificar-vencimentos-test'
      path: '/api/public/hooks/notificar-vencimentos-test'
      fullPath: '/api/public/hooks/notificar-vencimentos-test'
      preLoaderRoute: typeof ApiPublicHooksNotificarVencimentosTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_toyota/toyota/estoque/importar': {
      id: '/_authenticated/_toyota/toyota/estoque/importar'
      path: '/toyota/estoque/importar'
      fullPath: '/toyota/estoque/importar'
      preLoaderRoute: typeof AuthenticatedToyotaToyotaEstoqueImportarRouteImport
      parentRoute: typeof AuthenticatedToyotaRoute
    }
    '/_authenticated/_toyota/toyota/revisoes/nova': {
      id: '/_authenticated/_toyota/toyota/revisoes/nova'
      path: '/nova'
      fullPath: '/toyota/revisoes/nova'
      preLoaderRoute: typeof AuthenticatedToyotaToyotaRevisoesNovaRouteImport
      parentRoute: typeof AuthenticatedToyotaToyotaRevisoesRoute
    }
  }
}

interface AuthenticatedComprasRouteChildren {
  AuthenticatedComprasComprasIdRoute: typeof AuthenticatedComprasComprasIdRoute
  AuthenticatedComprasComprasConfiguracoesRoute: typeof AuthenticatedComprasComprasConfiguracoesRoute
  AuthenticatedComprasComprasNovoRoute: typeof AuthenticatedComprasComprasNovoRoute
  AuthenticatedComprasComprasIndexRoute: typeof AuthenticatedComprasComprasIndexRoute
}

const AuthenticatedComprasRouteChildren: AuthenticatedComprasRouteChildren = {
  AuthenticatedComprasComprasIdRoute: AuthenticatedComprasComprasIdRoute,
  AuthenticatedComprasComprasConfiguracoesRoute:
    AuthenticatedComprasComprasConfiguracoesRoute,
  AuthenticatedComprasComprasNovoRoute: AuthenticatedComprasComprasNovoRoute,
  AuthenticatedComprasComprasIndexRoute: AuthenticatedComprasComprasIndexRoute,
}

const AuthenticatedComprasRouteWithChildren =
  AuthenticatedComprasRoute._addFileChildren(AuthenticatedComprasRouteChildren)

interface AuthenticatedDocumentosRouteChildren {
  AuthenticatedDocumentosDocumentosRoute: typeof AuthenticatedDocumentosDocumentosRoute
}

const AuthenticatedDocumentosRouteChildren: AuthenticatedDocumentosRouteChildren =
  {
    AuthenticatedDocumentosDocumentosRoute:
      AuthenticatedDocumentosDocumentosRoute,
  }

const AuthenticatedDocumentosRouteWithChildren =
  AuthenticatedDocumentosRoute._addFileChildren(
    AuthenticatedDocumentosRouteChildren,
  )

interface AuthenticatedGestaoRouteChildren {
  AuthenticatedGestaoBacklogRoute: typeof AuthenticatedGestaoBacklogRoute
  AuthenticatedGestaoDashboardRoute: typeof AuthenticatedGestaoDashboardRoute
  AuthenticatedGestaoHistoricoRoute: typeof AuthenticatedGestaoHistoricoRoute
  AuthenticatedGestaoProjetosRoute: typeof AuthenticatedGestaoProjetosRoute
  AuthenticatedGestaoRoadmapRoute: typeof AuthenticatedGestaoRoadmapRoute
  AuthenticatedGestaoSolicitacoesRoute: typeof AuthenticatedGestaoSolicitacoesRoute
}

const AuthenticatedGestaoRouteChildren: AuthenticatedGestaoRouteChildren = {
  AuthenticatedGestaoBacklogRoute: AuthenticatedGestaoBacklogRoute,
  AuthenticatedGestaoDashboardRoute: AuthenticatedGestaoDashboardRoute,
  AuthenticatedGestaoHistoricoRoute: AuthenticatedGestaoHistoricoRoute,
  AuthenticatedGestaoProjetosRoute: AuthenticatedGestaoProjetosRoute,
  AuthenticatedGestaoRoadmapRoute: AuthenticatedGestaoRoadmapRoute,
  AuthenticatedGestaoSolicitacoesRoute: AuthenticatedGestaoSolicitacoesRoute,
}

const AuthenticatedGestaoRouteWithChildren =
  AuthenticatedGestaoRoute._addFileChildren(AuthenticatedGestaoRouteChildren)

interface AuthenticatedToyotaToyotaRevisoesRouteChildren {
  AuthenticatedToyotaToyotaRevisoesNovaRoute: typeof AuthenticatedToyotaToyotaRevisoesNovaRoute
}

const AuthenticatedToyotaToyotaRevisoesRouteChildren: AuthenticatedToyotaToyotaRevisoesRouteChildren =
  {
    AuthenticatedToyotaToyotaRevisoesNovaRoute:
      AuthenticatedToyotaToyotaRevisoesNovaRoute,
  }

const AuthenticatedToyotaToyotaRevisoesRouteWithChildren =
  AuthenticatedToyotaToyotaRevisoesRoute._addFileChildren(
    AuthenticatedToyotaToyotaRevisoesRouteChildren,
  )

interface AuthenticatedToyotaRouteChildren {
  AuthenticatedToyotaToyotaConfiguracoesRoute: typeof AuthenticatedToyotaToyotaConfiguracoesRoute
  AuthenticatedToyotaToyotaElegiveisRoute: typeof AuthenticatedToyotaToyotaElegiveisRoute
  AuthenticatedToyotaToyotaFilaPosvendasRoute: typeof AuthenticatedToyotaToyotaFilaPosvendasRoute
  AuthenticatedToyotaToyotaFilaPreparadorRoute: typeof AuthenticatedToyotaToyotaFilaPreparadorRoute
  AuthenticatedToyotaToyotaPainelRoute: typeof AuthenticatedToyotaToyotaPainelRoute
  AuthenticatedToyotaToyotaPainelGeralRoute: typeof AuthenticatedToyotaToyotaPainelGeralRoute
  AuthenticatedToyotaToyotaRegrasRoute: typeof AuthenticatedToyotaToyotaRegrasRoute
  AuthenticatedToyotaToyotaRevisoesRoute: typeof AuthenticatedToyotaToyotaRevisoesRouteWithChildren
  AuthenticatedToyotaToyotaEstoqueImportarRoute: typeof AuthenticatedToyotaToyotaEstoqueImportarRoute
}

const AuthenticatedToyotaRouteChildren: AuthenticatedToyotaRouteChildren = {
  AuthenticatedToyotaToyotaConfiguracoesRoute:
    AuthenticatedToyotaToyotaConfiguracoesRoute,
  AuthenticatedToyotaToyotaElegiveisRoute:
    AuthenticatedToyotaToyotaElegiveisRoute,
  AuthenticatedToyotaToyotaFilaPosvendasRoute:
    AuthenticatedToyotaToyotaFilaPosvendasRoute,
  AuthenticatedToyotaToyotaFilaPreparadorRoute:
    AuthenticatedToyotaToyotaFilaPreparadorRoute,
  AuthenticatedToyotaToyotaPainelRoute: AuthenticatedToyotaToyotaPainelRoute,
  AuthenticatedToyotaToyotaPainelGeralRoute:
    AuthenticatedToyotaToyotaPainelGeralRoute,
  AuthenticatedToyotaToyotaRegrasRoute: AuthenticatedToyotaToyotaRegrasRoute,
  AuthenticatedToyotaToyotaRevisoesRoute:
    AuthenticatedToyotaToyotaRevisoesRouteWithChildren,
  AuthenticatedToyotaToyotaEstoqueImportarRoute:
    AuthenticatedToyotaToyotaEstoqueImportarRoute,
}

const AuthenticatedToyotaRouteWithChildren =
  AuthenticatedToyotaRoute._addFileChildren(AuthenticatedToyotaRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedComprasRoute: typeof AuthenticatedComprasRouteWithChildren
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRouteWithChildren
  AuthenticatedGestaoRoute: typeof AuthenticatedGestaoRouteWithChildren
  AuthenticatedToyotaRoute: typeof AuthenticatedToyotaRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedComprasRoute: AuthenticatedComprasRouteWithChildren,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRouteWithChildren,
  AuthenticatedGestaoRoute: AuthenticatedGestaoRouteWithChildren,
  AuthenticatedToyotaRoute: AuthenticatedToyotaRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RegistrarRoute: RegistrarRoute,
  ApiPublicCronVerificarNotificacoesRoute:
    ApiPublicCronVerificarNotificacoesRoute,
  ApiPublicHooksNotificarVencimentosRoute:
    ApiPublicHooksNotificarVencimentosRoute,
  ApiPublicHooksNotificarVencimentosTestRoute:
    ApiPublicHooksNotificarVencimentosTestRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
